# +----------------------------------------------------+
# <              GravityReal by xAspired               >
# <                                                    >
# <           All rights are reserved by him           >
# <               Check license for more               >
# +----------------------------------------------------+
#
# !!These comments will be erased on the first creation of a Map!!
#

# Copy of Configuration File
# If something breaks, replace 'config.yml' with this one
database: #Only MySQL supported
  credentials:
    username: ''
    password: ''
    port: 3306
    database: ''
    dbUrl: 'localhost'

coins:
  use-playerpoints: true
  coins-per-win: 1

message-join: "&8|| &bGra&avity&7: Welcome to our minigame!" # Join Chat Message
game-prefix: "&8|| &bGra&avity&7 &8| &R" #Prefix
max-players: 10
min-players: 2
maps-per-game: 5 # Number of Maps for each game
duration-time: 300 # Should be set in seconds
lobbyspawn:
  spawnpoint:
    world: 0
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0