# +----------------------------------------------------+
# <              GravityReal by xAspired               >
# <                                                    >
# <           All rights are reserved by him           >
# <               Check license for more               >
# +----------------------------------------------------+
#
# !!These comments will be erased on the first creation of a Map!!
#

# Default Configuration File

# Priorities:
# Coins: PlayerPoints, MySQL, Local
# Stats: MySQL, Local
# Local is the fallback method when something doesn't work
database:
  storage: "mysql" #mysql, local
  credentials:
    username: ''
    password: ''
    port: 3306
    database: ''
    dbUrl: 'localhost'

coins:
  use-playerpoints: true # If true it will override the storage and use the playerpoints API
  coins-per-win: 1

messages: # !DO NOT CHANGE PLACEHOLDERS!
  message-join: "&7Welcome to our minigame!"
  game-prefix: "&8|| &bGra&avity&7 &8| &R"
  welcome-title: "&fWelcome to &bGra&avity"
  queue-title: "&fYou are now in &e&nqueue"
  teleporting-error: "&7There was a problem teleporting you into the correct spawnpoint. Please report it to a server admin."
  greetings-playing: "&fThanks for playing!"
  game-winner: "&7The winner is &e&n{PLAYER}&R&7 with {TIME}&7s"
  winner-message: "&d{PLAYER} &efinished the game!"
  actual-coins: "&eNow you have {COINS} coins."
  kick-reason-1: "Game is still in progress"
  scoreboard:
    your-stats: "&e&lYour Stats:"
    ranking: "&3&lRanking:"
    waiting: "&f{NUMBER}#  Waiting..."


max-players: 10
min-players: 2
maps-per-game: 5 # Number of Maps for each game
duration-time: 300 # Should be set in seconds
lobbyspawn:
  spawnpoint:
    world: 0
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0