# +----------------------------------------------------+
# <              GravityReal by xAspired               >
# <                                                    >
# <           All rights are reserved by him           >
# <               Check license for more               >
# +----------------------------------------------------+
#
# !!These comments will be erased on the first creation of a Map!!
#

# Default Configuration File
message-join: "&8|| &bGra&avity&7: Welcome to our minigame!" # Join Chat Message
max-players: 10
min-players: 2
maps-per-game: 5 # Number of Maps for each game
duration-time: 300 # Should be set in seconds
lobbyspawn:
  spawnpoint:
    world: 0
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0

maps: