name: GravityReal # the plugins name as it should appear in the plugin list /pl
version: 1.69 # the plugin's version
author: xAspired (GianMattia)
main: me.xaspired.GravityReal.Main
api-version: 1.17 # the version of the API you want to use, required starting with 1.13
# List of commands.
commands:
  gravity:
    description: Shows a list of possible command to do while admin
    usage: /<command>
    permission: gravityreal.admin
    permission-message: "You can't execute that command"
  spawn:
    description: Teleport player to Lobby Spawnpoint
    usage: /<command>
    permission: gravityreal.spawn
    permission-message: "You can't execute that command"
  debug:
    description: Lets Dev debugging on his code
    usage: /<command>
    permission: gravityreal.admin
    permission-message: "You can't execute that command"
  coords:
    description: Shows player's coordinates
    usage: /<command>
    permission: gravityreal.coords
    permission-message: "You can't execute that command"
  gmc:
    description: Sets player's gamemode to creative
    usage: /<command>
    permission: gravityreal.gamemode.creative
    permission-message: "You can't execute that command"